image: python:3.9

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python myblog/manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
