stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Running tests..."
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Здесь будет логика деплоя (например, Docker или SCP)"