image: python:3.9

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Listing files in current directory:"
    - ls -la
    - echo "Trying to change directory to myblog:"
    - cd myblog
    - echo "Listing files in myblog directory:"
    - ls -la
    - echo "Running tests..."
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Здесь будет логика деплоя (например, Docker или SCP)"
