global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '8032905593:AAHBD1GL1jQATHLN9Cr8S3bgSBrEZNf5WO8'
        chat_id: 1729543328
        message: |
          🚨 Alert: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}
          Severity: {{ .CommonLabels.severity }}
